# Symfony minmal version:
# - 3: 7.0.8
# - 4: 7.1.3
# - 5: 7.2.5
# - 6: 8.0.2

name: Symfony Bundle CI

on:
  push:
    branches: [ main ]
  pull_request:

  workflow_dispatch:

jobs:
  tests:
    environment: main
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']
        stability: [prefer-stable]
        minimum-stability: [stable]
        symfony-version: [7.2.*]
        is-current: [true]
        include:
          - php: '8.3'
            symfony-version: 7.2.*
            stability: prefer-stable
          - php: '8.4'
            symfony-version: 7.2.*
            stability: prefer-stable

    name: PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony-require }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-packages-${{ hashFiles('composer.lock') }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
          composer config minimum-stability ${{ matrix.minimum-stability }}
          composer update --no-interaction --prefer-dist

      - name: PHP-CS-Fixer
        continue-on-error: ${{ !matrix.is-current }}
        run: vendor/bin/php-cs-fixer fix --dry-run --ansi -vvv

      - name: PHP_CodeSniffer
        continue-on-error: ${{ !matrix.is-current }}
        run: vendor/bin/phpcs --report=code

      - name: PHPStan
        continue-on-error: ${{ !matrix.is-current }}
        run: vendor/bin/phpstan analyse src tests --level 9

      - name: Unit and Feature tests via PHPUnit
        env:
          SYMFONY_DEPRECATIONS_HELPER: weak
        run: vendor/bin/phpunit

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: sonarsource/sonarcloud-github-action@v2

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
